version: 2

jobs:
  build: 
    docker: 
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout # check out the code in the project directory
      - run: ./mvnw package